@startuml class diagram
'https://plantuml.com/class-diagram

class VendingMachine{
    -__SweetManager
    -__DrinkManager
    -__MoneyManager
    -__VendingMachinePrinter
    -__sProductsType : String
    -__init__(sm, dm, mm, vmp)
    +void StartVendingMachine()
    +void __CollectCoinsFromUser()
    +Product __GetProductSelectionFromUser()
    +void __HandlePurchase(Product)
    +void DumpProducts(sProductJsonFilePath, sDrinkJsonFilePath, sSweetJsonFilePath)
    +dProducts __GetProductsByType(sProductsType)
    +void __RemoveProduct(Product)
    +void __UpdateQuantity(Product)
    +bool __VmHaveEnoughChange(Product)
}

class VendingMachinePrinter{
    +void InvalidCoin()
    +void NotEnoughMoney(iPrice, iCustomerMoney)
    +void NotEnoughChange()
    +void InvalidProductUId()
    +void InitialMessage(sProductsType, AvailableDrinks, AvailableSweets, iCustomerMoney)
    +void ProductPayment(sProductName)
    +void ChangeMoney(iChangeMoney)
    +void CreatePrintListFromDict(dProducts)
}

class MoneyManager{
    -_iVmChangeMoney : Integer
    -_iCustomerMoney : Integer
    -_iCustomerChangeMoney : Integer
    -Just Getters - init from JSON
    -__init__(sMoneyJsonPath)
    +void DumpMoney(sJsonFilePath)
    +AddToCustomerMoney(x)
    +AddToVmChangeMoney(x)
    +bool CustomerHaveEnoughMoney(Product)
    +AddToCustomerChangeMoney(iProductPrice)
    +bool HaveEnoughChange()
}

class DrinkManager{
    -__init__(sProductsJsonFilePath)
    +void _AddProducts()
}

class SweetManager{
    -__init__(sProductsJsonFilePath)
    +void _AddProducts()
}

class Product{
    -_iUid : Integer
    -_sName : String
    -_iPrice : Integer
    -_iQuantity : Integer
    -_sProductFamily : String
    -__init__(iUid, sName, iPrice, iQuantity, sProductFamily)
    -Just Getters - init from JSON
    +void Reduce1FromQuantity()
}

class Drink{
    -__init__(iUid, sName, iPrice, iQuantity)
}

class Sweet{
    -__init__(iUid, sName, iPrice, iQuantity)
}

class Consts{
    CURRENCY_TYPE : String
    COINS_LIST : List
    JSON_DIR_PATH_TESTS : String
    JSON_DIR_PATH_PROGRAM : String
    PRODUCT_DATA_JSON_FILE : String
    MONEY_DATA_JSON_FILE : String
    PRODUCT_DATA_DUMP_JSON_FILE : String
    DRINK_DATA_DUMP_JSON_FILE : String
    SWEET_DATA_DUMP_JSON_FILE : String
    MONEY_DATA_DUMP_JSON_FILE : String
    DRINKS : String
    SWEETS : String
    ALL : String
}

abstract class ProductManager{
    - _dProducts : Dict
    -__init__(sProductsJsonFilePath)
    -Just Getters - init from JSON
    +void {abstract} _AddProducts()
    +lAvailableProducts GetAvailableProducts()
    +void _AddProduct(iUid, Product)
    +void RemoveProduct(iUid)
    +void DumpProducts(sJsonFilePath)
    +void UpdateQuantity(iProductId)
}

ProductManager <|-- DrinkManager
ProductManager <|-- SweetManager
Product <|-- Drink
Product <|-- Sweet
VendingMachine "1" *-- "1" DrinkManager : have >
VendingMachine "1" *-- "1" SweetManager : have >
VendingMachine "1" *-- "1" MoneyManager : have >
VendingMachine "1" *-- "1" VendingMachinePrinter : have >
DrinkManager "1" *-- "many" Drink :have >
SweetManager "1" *-- "many" Sweet :have >

@enduml