@startuml class diagram
'https://plantuml.com/class-diagram

class VendingMachine{
    -__ProductManager
    -__MoneyManager
    -__DataReader
    -__VendingMachinePrinter
    -__sChosenProductsType : String
    -__init__(pm, mm, vmp)
    +void StartVendingMachine()
    +void __CollectCoinsFromUser()
    +Product __GetProductSelectionFromUser()
    +void __HandlePurchase(Product)
    +bool __VmHaveEnoughChange(Product)
}

class VendingMachinePrinter{
    +void InvalidCoin()
    +void NotEnoughMoney(iPrice, iCustomerMoney)
    +void NotEnoughChange()
    +void InvalidProductUId()
    +void InitialMessage(sProductsType, iCustomerMoney)
    +void ProductPayment(sProductName)
    +void ChangeMoney(iChangeMoney)
    +void __Dict2PrintList(dProducts)
}

class MoneyManager{
    -__dMoney : Dictionary
    -_iVmChangeMoney : Integer
    -_iCustomerMoney : Integer
    -_iCustomerChangeMoney : Integer
    -Just Getters - init from JSON
    -__init__(sMoneyJsonPath)
    +void DumpMoney(sJsonFilePath)
    +AddToCustomerMoney(x)
    +AddToVmChangeMoney(x)
    +bool CustomerHaveEnoughMoney(Product)
    +AddToCustomerChangeMoney(iProductPrice)
    +bool HaveEnoughChange()
}

class DataReader{
    +dProducts ReadDataFromFile(sProductsJsonFilePath)
    +dMoney ReadMoneyDataFromFile(sMoneyJsonFilePath)
    +filteredProducts FilterData(self, Products, sProductType)
}

class Product{
    -_iUid : Integer
    -_sName : String
    -_iPrice : Integer
    -_iQuantity : Integer
    -_sProductFamily : String
    -__init__(iUid, sName, iPrice, iQuantity, sProductFamily)
    -Just Getters - init from JSON
    +void Reduce1FromQuantity()
}

class Drink{}

class Sweet{}

class Consts{
    CURRENCY_TYPE : String
    COINS_LIST : List
    JSON_DIR_PATH_TESTS : String
    JSON_DIR_PATH_PROGRAM : String
    PRODUCT_DATA_JSON_FILE : String
    MONEY_DATA_JSON_FILE : String
    PRODUCT_DATA_DUMP_JSON_FILE : String
    MONEY_DATA_DUMP_JSON_FILE : String
    DRINK : String
    SWEET : String
    ALL : String

    another few consts which used for Serialization
}

abstract class ProductManager{
    - _dProducts : Dict
    -__init__(sProductsJsonFilePath)
    -Just Getters - init from JSON
    +lAvailableProducts GetAvailableProducts()
    +void RemoveProduct(iUid)
    +void DumpProducts(sJsonFilePath)
    +void UpdateQuantity(iProductId)
}

Product <|-- Drink
Product <|-- Sweet
VendingMachine "1" *-- "1" ProductManager : have >
VendingMachine "1" *-- "1" MoneyManager : have >
VendingMachine "1" *-- "1" VendingMachinePrinter : have >
VendingMachine "1" *-- "1" DataReader : have >
ProductManager "1" *-- "1" DataReader : have >
ProductManager "1" *-- "many" Product : have >

@enduml